#!/bin/bash

#uSrteam settings
#RTMP_URL=rtmp://1.21705518.fme.ustream.tv/ustreamVideo/21705518
#STREAM_KEY=fKb9NJUycD2unefr9JhukXybZBRSB3Wq

#youtube settings - 
RTMP_URL=rtmp://a.rtmp.youtube.com/live2
STREAM_KEY=keiths-pi-tutor-0012.vtku-wa9a-mgvj-206c
while :
do
    raspivid -n -vf -hf -t 0 -w 590 -h 360 -fps 25 -b 500000 -o - | ffmpeg -i - -force_key_frames expr:gte\(t,n_forced*3\) -vcodec copy -an -metadata title="Streaming from raspberry pi camera" -f flv $RTMP_URL/$STREAM_KEY
    sleep 2
done
